export const AVATAR_RIG_COLORS = {
  canvasBackground: '#f7f5ef',
  line: '#262626',
  skin: '#f8e6e2',
  hair: '#7c716b',
  hairLight: '#9a7a74',
  sclera: '#ffffff',
  eyeBall: '#558bd6',
  eyeLight: '#ffffff',
  lowerEyelidColor: 'transparent',
  lowerEyelidLine: '#845a55',
  upperEyelid: '#544644',
  eyelid: '#bb8575',
  eyebrow: '#47403d',
  nose: '#b36161',
  mouth: '#936266',
  clothingTop: '#3368e2',
  clothingBottom: '#ffffff',
  clothingBottomSideDeco: '#808080',
  accessory: '#ffffff',
} as const;

export const AVATAR_PORTRAIT_RIG_LAYOUT = {
  faceCenter: { x: 0, y: 26 },
  groups: {
    eyes: { x: 0, y: -10 },
    hair: { x: 0, y: -54 },
  },
  parts: {
    face: { x: 0, y: 0 },
    ear: { x: -36, y: -6 },
    sclera: { x: -10, y: -10 },
    eyeBall: { x: -14, y: -13 },
    eyeLight: { x: -8, y: -12 },
    eyebrow: { x: -8, y: -15 },
    eyelid: { x: -10, y: -21 },
    upperEyelid: { x: -10, y: -19 },
    lowerEyelid: { x: -14, y: -5 },
    nose: { x: -2, y: 25 },
    mouth: { x: 0, y: 42 },
    backHairBottom: { x: 0, y: 27 },
    backHairTop: { x: 0, y: -93 },
    bangs: { x: 0, y: -50 },
    hairLight: { x: 0, y: -50 },
    accessory: { x: 0, y: -35 },
  },
  partsByOption: {
    backHairBottom: {
      1: { x: 0, y: 0 },
      2: { x: 0, y: 0 },
      3: { x: 0, y: 0 },
      7: { x: -6, y: -8 },
    },
    backHairTop: {
      1: { x: 0, y: 0 },
      2: { x: 0, y: 0 },
      3: { x: 0, y: 0 },
      7: { x: -3, y: -6 },
    },
    bangs: {
      1: { x: 0, y: 0 },
      2: { x: 0, y: 0 },
      3: { x: 0, y: 0 },
      7: { x: -17, y: -8.5 },
    },
  },
  accessoriesByOption: {
    sideHair: {
      1: { x: 0, y: 0 },
      2: { x: 12, y: 18 },
      3: { x: 0, y: 0 },
      4: { x: 0, y: 0 },
      5: { x: 0, y: 0 },
      6: { x: 34.5, y: -37 },
    },
    ponytail: {
      1: { x: 0, y: 0 },
      2: { x: 0, y: 0 },
      3: { x: 0, y: 0 },
      4: { x: 0, y: 0 },
      5: { x: 0, y: 0 },
    },
    accessory: {
      1: { x: 0, y: 0 },
      2: { x: 0, y: 0 },
      3: { x: 0, y: 0 },
      4: { x: 0, y: 0 },
      5: { x: 0, y: 0 },
    },
    skinMarking: {
      1: { x: -20, y: 85 },
    },
  },
  mirrored: {
    eyeDistance: 50,
    defaultEyeLightDistance: 45,
    earDistance: 111,
    accessoryDistance: 60,
    accessoryY: 30,
    eyebrowY: -12,
    upperEyelidY: -7,
    lowerEyelidY: 8,
  },
} as const;
