export const DEFAULT_CELL_SIZE = 20;
export const TOWN_MAP_CELL_SIZE = 10;
export const CHARACTER_RADIUS_RATIO = 0.28;
export const TOWN_MAP_CHARACTER_RENDER_SCALE = 4;
export const DEFAULT_ENTITY_LAYER_RANK = 50;
export const FLOATING_UI_LAYER_RANK = 100;
