import { MINI_ACCESSORY_SLOT_Z_INDEX } from '../miniAvatarRig';

export const MINI_HEAD_BACK_Z_INDEX = MINI_ACCESSORY_SLOT_Z_INDEX.behindBody;
export const MINI_HEAD_ON_SKIN_Z_INDEX = MINI_ACCESSORY_SLOT_Z_INDEX.onSkin;
export const MINI_HEAD_BODY_FRONT_Z_INDEX = MINI_ACCESSORY_SLOT_Z_INDEX.frontBody;
export const MINI_HEAD_MAIN_Z_INDEX = 10;
export const MINI_HEAD_FRONT_FACE_Z_INDEX = MINI_ACCESSORY_SLOT_Z_INDEX.frontFace;
export const MINI_HEAD_BANGS_Z_INDEX = 30;
export const MINI_HEAD_FRONT_BANGS_Z_INDEX = MINI_ACCESSORY_SLOT_Z_INDEX.frontBangs;
export const MINI_BACK_HEAD_MAIN_Z_INDEX = -2;
